runtime: nodejs14

instance_class: F1

entrypoint: node dist/index.js

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

network:
  session_affinity: true