name: Deployment

on:
  push:

jobs:
  deployment:
    runs-on: ubuntu-latest
    name: Deployment
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Make .env
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_YOUTUBE_DATA_API_KEY: ${{ secrets.YOUTUBE_DATA_API_KEY }}

      - name: Build
        run: npm run build

      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@main
        with:
          working_directory: ./dist
          deliverables: ../app.yaml
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials: ${{ secrets.GCP_SA_KEY }}
